# Manage Zanata definition 

IF(DEFINED _MANAGE_ZANATA_DEFINITION_)
    RETURN()
ENDIF(DEFINED _MANAGE_ZANATA_DEFINITION_)

## ZANATA_OPTIONS_NAME_<OPTION> <HAS_VALUE> [<defaultvalue>]
## OPTION_ID: Start with - : mvn/zanata-cli options
##            Start with  : cmake-fedora options
##            Others       : zanata-cli formatted long options
## HAS_VALUE: 0 (no value)
##            1 (optional value)
##            2 (mandatory value)

SET(ZANATA_OPTION_NAME_YES 0)
SET(ZANATA_OPTION_NAME_BATCH 0)
SET(ZANATA_OPTION_NAME_ERRORS 0)
SET(ZANATA_OPTION_NAME_DEBUG 0)
SET(ZANATA_OPTION_NAME_CLEAN_ZANATA_XML  0)
SET(ZANATA_OPTION_NAME_CLIENT_COMMAND  2 "/usr/bin/zanata")
SET(ZANATA_OPTION_NAME_ZANATA_EXECUTABLE 2 "/usr/bin/zanata")
SET(ZANATA_OPTION_NAME_COPY_TRANS 1 "true")
SET(ZANATA_OPTION_NAME_CREATE_SKELETONS 1 "true")
SET(ZANATA_OPTION_NAME_DISABLE_SSL_CERT 1 "true")
SET(ZANATA_OPTION_NAME_ENCODE_TABS 1 "true")
SET(ZANATA_OPTION_NAME_EXCLUDES "**/*_*.properties")
SET(ZANATA_OPTION_NAME_GENERATE_ZANATA_XML 0)
SET(ZANATA_OPTION_NAME_INCLUDES 2 "**/*.properties")
SET(ZANATA_OPTION_NAME_LOCALES 2 "de;es;fr;it;ja;kr;zh-CN;zh-TW")
SET(ZANATA_OPTION_NAME_PROJECT 2 "${PROJECT_NAME}")
SET(ZANATA_OPTION_NAME_PROJECT_CONFIG 2 "${CMAKE_CURRENT_BINARY_DIR}/zanata.xml")
SET(ZANATA_OPTION_NAME_PROJECT_DESC 2 "${PRJ_SUMMARY}")
SET(ZANATA_OPTION_NAME_PROJECT_NAME 2 "${PROJECT_NAME}")
SET(ZANATA_OPTION_NAME_PROJECT_TYPE 2 "gettext")
SET(ZANATA_OPTION_NAME_SRC_DIR  2 ".")
SET(ZANATA_OPTION_NAME_TRANS_DIR 2 ".")
SET(ZANATA_OPTION_NAME_TRANS_DIR_PULL 2 "${CMAKE_CURRENT_BINARY_DIR}")
SET(ZANATA_OPTION_NAME_USER_CONFIG 2 "$ENV{$HOME}/.config/zanata.ini")
SET(ZANATA_OPTION_NAME_VERSION 2 "master")

SET(ZANATA_OPTION_NAME_ALIAS_YES "BATCH")
SET(ZANATA_OPTION_NAME_ALIAS_CLIENT_COMMAND "ZANATA_EXECUTABLE")

## ZANATA_<BACKEND>_<SUBCOMMAND>_OPTION_NAME_<OPTION> <ACTUAL_NAME_IN_SUBCOMMAND>
SET(ZANATA_MVN_PUT_PROJECT_OPTION_NAME_PROJECT "PROJECT_SLUG")
SET(ZANATA_MVN_PUT_PROJECT_OPTION_NAME_PROJECT_TYPE "DEFAULT_PROJECT_TYPE")
SET(ZANATA_MVN_PUT_VERSION_OPTION_NAME_PROJECT "VERSION_PROJET")
SET(ZANATA_MVN_PUT_VERSION_OPTION_NAME_VERSION "VERSION_SLUG")

SET(ZANATA_MVN_PUT_PROJECT_MANDATORY_OPTIONS "PROJECT" "PROJECT_NAME" "PROJECT_DESC" "PROJECT_TYPE")
SET(ZANATA_MVN_PUT_VERSION_MANDATORY_OPTIONS "PROJECT" "VERSION")

